apiVersion: v1
kind: Pod
metadata:
  name: server-www
  namespace: instavote
  labels:
    app: apache
    role: apache
    version: v1
spec:
  containers:
    - name: server-www
      image: gromeka/gromrepo:v1
      ports:
        - containerPort: 80
          protocol: TCP
      
